Mall/Mall/urls.py
from django.conf.urls import url, include

# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^mall/', include('userinfo.urls', namespace='mall')),
    url(r"^captcha/",include('captcha.urls'))
]

Mall/userinfo/urls.py
from django.conf.urls import url
from userinfo import views

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login_/$',views.login_,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^list/$',views.list,name='list'),
    url(r'^list1/$',views.list1,name='list1'),
    url(r'^list2/$',views.list2,name='list2'),
    url(r'^list3/$',views.list3,name='list3'),
    url(r'^list4/$',views.list4,name='list4'),
    url(r'^list5/$',views.list5,name='list5'),
    url(r'^detail/$',views.detail,name='detail'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^center/$',views.center,name='center'),
    url(r'^edit/$',views.edit,name='edit'),
    url(r'^add_cart/$',views.add_cart,name='add_cart'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^cart_price/$',views.cart_price,name='cart_price'),
    url(r'^cart_num/%',views.cart_num,name='cart_num'),
    url(r'^change_cart/$',views.change_cart,name='change_cart'),
    url(r'^delete_cart/$',views.delete_cart,name='delete_cart'),
    url(r'^change_status_cart/$',views.change_status_cart,name='change_status_cart'),
    url(r'^order_center/$',views.order_center,name='order_center')
]

Mall/templates/dingdanzhongxin.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <meta name="author" content="order by dede58.com"/>
		<title>小米商城-个人中心</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
	<body>
	<!-- start header -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="">我的订单</a></div>
					<div class="fr">
						 {% if request.session.username %}
				<div class="right fr">
					<div class="gouwuche fr"><a href="{% url 'mall:cart' %}">购物车</a></div>
					<div class="fr">
						<ul>
							<li><a href="" target="_blank">{{ request.session.username }}</a></li>
							<li>|</li>
							<li><a href="{% url 'mall:logout' %}" target="_blank" >退出</a></li>
							<li>|</li>
							<li><a href="">消息通知</a></li>
						</ul>
					</div>
					<div class="clear"></div>
				</div>
                {% else %}
                <div class="right fr">
					<div class="gouwuche fr"><a href="{% url 'mall:cart' %}">购物车</a></div>
					<div class="fr">
						<ul>
							<li><a href="{% url 'mall:login' %}" target="_blank">登录</a></li>
							<li>|</li>
							<li><a href="{% url 'mall:register' %}" target="_blank" >注册</a></li>
							<li>|</li>
							<li><a href="">消息通知</a></li>
						</ul>
					</div>
					<div class="clear"></div>
				</div>
                {% endif %}
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->
	<!-- start banner_x -->
		<div class="banner_x center">
			<a href="{% url 'mall:index' %}" target="_blank"><div class="logo fl"></div></a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="{% url 'mall:list' %}">小米手机</a></li>
					<li><a href="{% url 'mall:list1' %}">红米</a></li>
					<li><a href="{% url 'mall:list2' %}">平板·笔记本</a></li>
					<li><a href="{% url 'mall:list3' %}">电视</a></li>
{#					<li><a href="">盒子·影音</a></li>#}
					<li><a href="{% url 'mall:list4' %}">路由器</a></li>
					<li><a href="{% url 'mall:list5' %}">智能硬件</a></li>
					<li><a href="https://www.mi.com/service/">服务</a></li>
					<li><a href="http://www.xiaomi.cn/">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->
<!-- self_info -->
	<div class="grzxbj">
		<div class="selfinfo center">
		<div class="lfnav fl">
			<div class="ddzx">订单中心</div>
			<div class="subddzx">
				<ul>
					<li><a href="" style="color:#ff6700;font-weight:bold;">我的订单</a></li>
{#					<li><a href="">意外保</a></li>#}
{#					<li><a href="">团购订单</a></li>#}
{#					<li><a href="">评价晒单</a></li>#}
				</ul>
			</div>
			<div class="ddzx">个人中心</div>
			<div class="subddzx">
				<ul>
					<li><a href="{% url 'mall:center' %}">我的个人中心</a></li>
{#					<li><a href="">消息通知</a></li>#}
{#					<li><a href="">优惠券</a></li>#}
					<li><a href="">收货地址</a></li>
				</ul>
			</div>
		</div>
		<div class="rtcont fr">
			<div class="ddzxbt">交易订单</div>
			<div class="ddxq">
				<div class="ddspt fl"><img src="{% static 'image/gwc_xiaomi6.jpg' %}" alt=""></div>
				<div class="ddbh fl">订单号:1705205643098724</div>
				<div class="ztxx fr">
					<ul>
						<li>已发货</li>
						<li>￥2499.00</li>
						<li>2017/05/20 13:30</li>
						<li><a href="">订单详情></a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="clear"></div>
			</div>
			<div class="ddxq">
				<div class="ddspt fl"><img src="{% static 'image/liebiao_hongmin4_dd.jpg' %}" alt=""></div>
				<div class="ddbh fl">订单号:170526435444865</div>
				<div class="ztxx fr">
					<ul>
						<li>已发货</li>
						<li>￥1999.00</li>
						<li>2017/05/26 14:02</li>
						<li><a href="">订单详情></a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="clear"></div>
		</div>
	</div>
<!-- self_info -->
		
		<footer class="mt20 center">			
			<div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
			<div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div> 
			<div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>
		</footer>
	</body>
</html>

Mall/templates/liebiao.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <meta name="author" content="order by dede58.com"/>
		<title>小米手机列表</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
	<body>
	<!-- start header -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				 {% if request.session.username %}
				<div class="right fr">
					<div class="gouwuche fr"><a href="{% url 'mall:cart' %}">购物车</a></div>
					<div class="fr">
						<ul>
							<li><a href="{% url 'mall:center' %}" target="_blank">{{ request.session.username }}</a></li>
							<li>|</li>
							<li><a href="{% url 'mall:logout' %}" target="_blank" >退出</a></li>
							<li>|</li>
							<li><a href="">消息通知</a></li>
						</ul>
					</div>
					<div class="clear"></div>
				</div>
                {% else %}
                <div class="right fr">
					<div class="gouwuche fr"><a href="{% url 'mall:cart' %}">购物车</a></div>
					<div class="fr">
						<ul>
							<li><a href="{% url 'mall:login' %}" target="_blank">登录</a></li>
							<li>|</li>
							<li><a href="{% url 'mall:register' %}" target="_blank" >注册</a></li>
							<li>|</li>
							<li><a href="">消息通知</a></li>
						</ul>
					</div>
					<div class="clear"></div>
				</div>
                {% endif %}
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->

<!-- start banner_x -->
		<div class="banner_x center">
			<a href="{% url 'mall:index' %}" target="_blank"><div class="logo fl"></div></a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="{% url 'mall:list' %}">小米手机</a></li>
					<li><a href="{% url 'mall:list1' %}">红米</a></li>
					<li><a href="{% url 'mall:list2' %}">平板·笔记本</a></li>
					<li><a href="{% url 'mall:list3' %}">电视</a></li>
{#					<li><a href="">盒子·影音</a></li>#}
					<li><a href="{% url 'mall:list4' %}">路由器</a></li>
					<li><a href="{% url 'mall:list5' %}">智能硬件</a></li>
					<li><a href="https://www.mi.com/service/">服务</a></li>
					<li><a href="http://www.xiaomi.cn/">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->

	<!-- start banner_y -->
	<!-- end banner -->

	<!-- start danpin -->
		<div class="danpin center">

			<div class="biaoti center"></div>

			<div class="main center">
                {% for i in new_goods %}
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">

                    <div class="sub_mingxing"><a href="{% url 'mall:detail'  %}?id={{ i.id }}" target="_blank"><img src="/static/{{ i.picture }}"></a></div>
					<div class="pinpai"><a href="{% url 'mall:detail' %}" target="_blank">{{ i.title }}</a></div>
					<div class="youhui">{{ i.commments }}</div>
					<div class="jiage">{{ i.price }}元</div>

				</div>
                {% endfor %}
{#                {% for g in goods %}#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="/static/{{ g.picture }}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">{{ g.title }}</a></div>#}
{#					<div class="youhui">{{ g.commments }}</div>#}
{#					<div class="jiage">{{ g.price }}</div>#}
{#				</div>#}
{#                {% endfor %}#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="{% static 'image/liebiao_xiaomint2.jpg' %}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">小米Note 2</a></div>#}
{#					<div class="youhui">5月9日-20日 小米Note 2 享花呗12期分期免息</div>#}
{#					<div class="jiage">2799.00元</div>#}
{#				</div>#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="{% static 'image/liebiao_xiaomimix.jpg' %}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">小米MIX</a></div>#}
{#					<div class="youhui">5月9日-20日小米MIX 享花呗12期分期免息</div>#}
{#					<div class="jiage">3499.00元</div>#}
{#				</div>#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="{% static 'image/liebiao_xiaomi5s.jpg' %}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">小米5s</a></div>#}
{#					<div class="youhui">“暗夜之眼”超感光相机 / 无孔式超声波</div>#}
{#					<div class="jiage">1999.00元</div>#}
{#				</div>#}
{##}
{#				<div class="clear"></div>#}
{#			</div>#}
{#			<div class="main center mb20">#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="{% static 'image/liebiao_xiaomi5.jpg' %}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">小米手机5</a></div>#}
{#					<div class="youhui">骁龙820处理器 / UFS 2.0 闪存</div>#}
{#					<div class="jiage">1799.00元</div>#}
{#				</div>#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="{% static 'image/liebiao_hongmin4.jpg' %}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">红米Note 4</a></div>#}
{#					<div class="youhui">十核旗舰处理器 / 全金属一体化机身 </div>#}
{#					<div class="jiage">1399.00元</div>#}
{#				</div>#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="{% static 'image/pinpai3.png' %}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">小米手机5 64GB</a></div>#}
{#					<div class="youhui">5月9日-10日，下单立减100元</div>#}
{#					<div class="jiage">1799元</div>#}
{#				</div>#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="{% static 'image/liebiao_hongmin42.jpg' %}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">红米4</a></div>#}
{#					<div class="youhui">2.5D 玻璃，金属一体化机身</div>#}
{#					<div class="jiage">999.00元</div>#}
{#				</div>#}
{#				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">#}
{#					<div class="sub_mingxing"><a href=""><img src="{% static 'image/liebiao_hongmin4x.jpg' %}" alt=""></a></div>#}
{#					<div class="pinpai"><a href="">红米Note 4X 全网通版</a></div>#}
{#					<div class="youhui">多彩金属 / 4100mAh 超长续航</div>#}
{#					<div class="jiage">1299.00元</div>#}
{#				</div>#}
				
				<div class="clear"></div>
			</div>

		</div>


		<footer class="mt20 center">			
			<div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
			<div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div> 
			<div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>

		</footer>

	<!-- end danpin -->


	</body>
</html>

Mall/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <meta name="author" content="order by dede58.com"/>
		<title>会员登录</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
        <script src="{% static 'js/jquery.min.js' %}"></script>
	</head>
	<body>
		<!-- login -->
		<div class="top center">
			<div class="logo center">
				<a href="{% url 'mall:index' %}" target="_blank"><img src="{% static 'image/mistore_logo.png' %}" alt=""></a>
			</div>
		</div>
		<form  method="post" action="{% url 'mall:login' %}" class="form center">
        {% csrf_token %}
		<div class="login">
			<div class="login_center">
				<div class="login_top">
					<div class="left fl">会员登录</div>
					<div class="right fr">您还不是我们的会员？<a href="{% url 'mall:register' %}" target="_self">立即注册</a></div>
					<div class="clear"></div>
					<div class="xian center"></div>
				</div>
				<div class="login_main center">
					<div class="username">用户名:&nbsp;<input class="shurukuang" type="text" name="username" placeholder="请输入你的用户名"/></div>
					<div class="username">密&nbsp;&nbsp;&nbsp;&nbsp;码:&nbsp;<input class="shurukuang" type="password" name="password" placeholder="请输入你的密码"/></div>
                    <div class="username" style="width: 600px">验证码:{{ new_user.captcha }}</div>
                    <div class='username'   ><a href="{% url 'mall:login' %}">看不清?刷新一下</a></div>
						<div class="clear"></div>
				</div>
				<div class="login_submit">
					<input class="submit" type="submit" name="submit" value="立即登录" >
				</div>

			</div>
		</div>
		</form>
{#        <script>#}
{#            $('button').click(function (ev) {#}
{#                ev.preventDefault()#}
{#                $.post("{% url 'mall:getcode' %}",$('#form1').serialize())#}
{#            })#}
{#        </script>#}
		<footer>
			<div class="copyright">简体 | 繁体 | English | 常见问题</div>
			<div class="copyright">小米公司版权所有-京ICP备10046444-<img src="{% static 'image/ghs.png' %}" alt="">京公网安备11010802020134号-京ICP证110507号</div>

		</footer>
	</body>
</html>

Mall/templates/self_info.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <meta name="author" content="order by dede58.com"/>
		<title>小米商城-个人中心</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
	<body>
	<!-- start header -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="{% url 'mall:order_center' %}">我的订单</a></div>
					<div class="fr">
						{% if request.session.username %}
				<div class="right fr">
{#					<div class="gouwuche fr"><a href="{% url 'mall:cart' %}">购物车</a></div>#}
					<div class="fr">
						<ul>
							<li><a href="{% url 'mall:center' %}" target="_blank">{{ request.session.username }}</a></li>
							<li>|</li>
							<li><a href="{% url 'mall:logout' %}" target="_blank" >退出</a></li>
							<li>|</li>
							<li><a href="">消息通知</a></li>
						</ul>
					</div>
					<div class="clear"></div>
				</div>
                {% else %}
                <div class="right fr">
					<div class="gouwuche fr"><a href="{% url 'mall:cart' %}">购物车</a></div>
					<div class="fr">
						<ul>
							<li><a href="{% url 'mall:login' %}" target="_blank">登录</a></li>
							<li>|</li>
							<li><a href="{% url 'mall:register' %}" target="_blank" >注册</a></li>
							<li>|</li>
							<li><a href="">消息通知</a></li>
						</ul>
					</div>
					<div class="clear"></div>
				</div>
                {% endif %}
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->
	<!-- start banner_x -->
		<div class="banner_x center">
			<a href="{% url 'mall:index' %}" target="_blank"><div class="logo fl"></div></a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="{% url 'mall:list' %}">小米手机</a></li>
					<li><a href="{% url 'mall:list1' %}">红米</a></li>
					<li><a href="{% url 'mall:list2' %}">平板·笔记本</a></li>
					<li><a href="{% url 'mall:list3' %}">电视</a></li>
{#					<li><a href="">盒子·影音</a></li>#}
					<li><a href="{% url 'mall:list4' %}">路由器</a></li>
					<li><a href="{% url 'mall:list5' %}">智能硬件</a></li>
					<li><a href="https://www.mi.com/service/">服务</a></li>
					<li><a href="http://www.xiaomi.cn/">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->
<!-- self_info -->
	<div class="grzxbj">
		<div class="selfinfo center">
		<div class="lfnav fl">
			<div class="ddzx">订单中心</div>
			<div class="subddzx">
				<ul>
					<li><a href="{% url 'mall:order_center' %}" >我的订单</a></li>
{#					<li><a href="">意外保</a></li>#}
{#					<li><a href="">团购订单</a></li>#}
{#					<li><a href="">评价晒单</a></li>#}
				</ul>
			</div>
			<div class="ddzx">个人中心</div>
			<div class="subddzx">
				<ul>
					<li><a href="{% url 'mall:center' %}" style="color:#ff6700;font-weight:bold;">我的个人中心</a></li>
{#					<li><a href="">消息通知</a></li>#}
{#					<li><a href="">优惠券</a></li>#}
					<li><a href="">收货地址</a></li>
				</ul>
			</div>
		</div>
		<div class="rtcont fr">
			<div class="grzlbt ml40">我的资料</div>
			<div class="subgrzl ml40"><span>昵称</span><span>{{ request.session.username }}</span><span><a href="{% url 'mall:edit' %}">编辑</a></span></div>
			<div class="subgrzl ml40"><span>手机号</span><span>{{ request.session.phone }}</span><span><a href="{% url 'mall:edit' %}">编辑</a></span></div>
			<div class="subgrzl ml40"><span>密码</span><span>************</span><span><a href="">编辑</a></span></div>
			<div class="subgrzl ml40"><span>个性签名</span><span>一支穿云箭，千军万马来相见！</span><span><a href="">编辑</a></span></div>
			<div class="subgrzl ml40"><span>我的爱好</span><span>游戏，音乐，旅游，健身</span><span><a href="">编辑</a></span></div>
			<div class="subgrzl ml40"><span>收货地址</span><span>浙江省杭州市江干区19号大街571号</span><span><a href="">编辑</a></span></div>
			
		</div>
		<div class="clear"></div>
		</div>
	</div>
<!-- self_info -->
		
		<footer class="mt20 center">			
			<div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
			<div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div> 
			<div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>
		</footer>
	</body>
</html>